exports.config = {
    appium: { command: 'appium' },
    runner: 'local',
    port: 4723,
    specs: ['./*.test.js'],
    path: '/wd/hub/',
    exclude: [],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: '',
        appiumVersion: '1.22.0',
        platformName: 'Android',
        platformVersion: '11',
        acceptInsecureCerts: true,
        deviceName: 'emulator-5554',
        appPackage: 'com.appium',
        appActivity: ".MainActivity",
        // app: "../android/app/build/outputs/apk/debug/app-debug.apk",
        orientation: 'PORTRAIT',
        automationName: 'UiAutomator2',
        chromedriverUseSystemExecutable: true,
        ignoreHiddenApiPolicyError: true,
        noReset: true,
        enableWebviewDetailsCollection: true,
    }],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://127.0.0.1',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: [
        [
          'native-app-compare',
          {
            baselineFolder: 'test/baseline',
            formatImageName: '{tag}-{logName}-{width}x{height}',
            screenshotPath: '.tmp/',
            savePerInstance: true,
            autoSaveBaseline: true,
            blockOutStatusBar: true,
            blockOutToolBar: true,
            isHybridApp: true,
          },
        ],
      ],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
}
